// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {versionmanager} from '../models';
import {migrator} from '../models';

export function AnalyzeCleanable():Promise<Array<models.CleanableItem>>;

export function CleanItems(arg1:Array<models.CleanableItem>):Promise<number>;

export function DetectVersionManager(arg1:string):Promise<versionmanager.VersionManagerConflict>;

export function FetchOfficialVersions(arg1:string):Promise<versionmanager.ToolVersionCatalog>;

export function GetDiskInfo():Promise<Array<models.DiskInfo>>;

export function GetEnvSummary(arg1:string):Promise<models.EnvSummary>;

export function GetEnvs():Promise<Array<models.Env>>;

export function GetHistory(arg1:number):Promise<Array<models.HistoryEntry>>;

export function GetMetricSnapshots(arg1:string,arg2:string,arg3:number):Promise<Array<models.MetricSnapshot>>;

export function GetSettings():Promise<models.AppSettings>;

export function InstallVersion(arg1:string,arg2:string,arg3:string):Promise<versionmanager.VersionOperationResult>;

export function ListToolVersions():Promise<Array<versionmanager.ToolVersionState>>;

export function ManageEnv(arg1:string):Promise<models.Env>;

export function Migrate(arg1:number,arg2:string,arg3:boolean):Promise<migrator.MigrationResult>;

export function PreviewVersionInstall(arg1:string,arg2:string):Promise<versionmanager.VersionInstallPlan>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function ScanAll():Promise<Array<models.EnvSummary>>;

export function SwitchVersion(arg1:string,arg2:number):Promise<versionmanager.VersionOperationResult>;

export function UninstallVersion(arg1:number,arg2:boolean):Promise<versionmanager.VersionOperationResult>;

export function UnmanageEnv(arg1:string):Promise<models.Env>;
