// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {migrator} from '../models';

export function AnalyzeCleanable():Promise<Array<models.CleanableItem>>;

export function CleanItems(arg1:Array<models.CleanableItem>):Promise<number>;

export function GetDiskInfo():Promise<Array<models.DiskInfo>>;

export function GetEnvSummary(arg1:string):Promise<models.EnvSummary>;

export function GetEnvs():Promise<Array<models.Env>>;

export function GetHistory(arg1:number):Promise<Array<models.HistoryEntry>>;

export function GetSettings():Promise<models.AppSettings>;

export function Migrate(arg1:number,arg2:string,arg3:boolean):Promise<migrator.MigrationResult>;

export function SaveSettings(arg1:models.AppSettings):Promise<void>;

export function ScanAll():Promise<Array<models.EnvSummary>>;
