// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeCleanable() {
  return window['go']['main']['App']['AnalyzeCleanable']();
}

export function CleanItems(arg1) {
  return window['go']['main']['App']['CleanItems'](arg1);
}

export function GetDiskInfo() {
  return window['go']['main']['App']['GetDiskInfo']();
}

export function GetEnvSummary(arg1) {
  return window['go']['main']['App']['GetEnvSummary'](arg1);
}

export function GetEnvs() {
  return window['go']['main']['App']['GetEnvs']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetMetricSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMetricSnapshots'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ManageEnv(arg1) {
  return window['go']['main']['App']['ManageEnv'](arg1);
}

export function Migrate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Migrate'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanAll() {
  return window['go']['main']['App']['ScanAll']();
}

export function UnmanageEnv(arg1) {
  return window['go']['main']['App']['UnmanageEnv'](arg1);
}
